export function getPanelCopy(language: string) {
  const isChinese = language === "zh-CN";
  const base = {
    noAttachedDocument: "No XML document is currently attached to the preview.",
    incompleteNodeEdit: "The webview sent an incomplete node edit request.",
    nodeAttributesUnchanged: "Node attributes already match the current XML.",
    nodeAttributesApplied: "Node attributes applied.",
    nodeAttributesFailed: "Failed to apply node attributes.",
    noAttachedDocumentWarning: "BTreeTool: No XML document is attached to the preview.",
    incompleteTreeNodesModel: "The webview sent an incomplete TreeNodesModel update request.",
    treeNodesModelUnchanged: "TreeNodesModel already matches the current XML.",
    treeNodesModelUpdated: "TreeNodesModel updated.",
    treeNodesModelFailed: "Failed to update TreeNodesModel.",
    incompleteBehaviorTreeCreate: "The webview sent an incomplete BehaviorTree create request.",
    createBehaviorTreeEmptyName: "BehaviorTree ID cannot be empty.",
    createBehaviorTreeDuplicateName: (treeId: string) => `BehaviorTree "${treeId}" already exists.`,
    behaviorTreeCreateUnchanged: "BehaviorTree already exists.",
    behaviorTreeCreated: "BehaviorTree created.",
    behaviorTreeCreateFailed: "Failed to create BehaviorTree.",
    incompleteBehaviorTreeDelete: "The webview sent an incomplete BehaviorTree delete request.",
    behaviorTreeDeleteUnchanged: "BehaviorTree was already removed.",
    behaviorTreeDeleted: "BehaviorTree removed.",
    behaviorTreeDeleteFailed: "Failed to remove BehaviorTree.",
    incompleteNodeMove: "The webview sent an incomplete node move request.",
    nodeOrderUnchanged: "Node order already matches the current XML.",
    nodeOrderUpdated: "Node order updated.",
    nodeOrderFailed: "Failed to reorder node.",
    incompleteNodeCreate: "The webview sent an incomplete node create request.",
    nodeCreateUnchanged: "Node already matches the target position.",
    nodeCreated: "Node created.",
    nodeCreateFailed: "Failed to create node.",
    incompleteNodeCopy: "The webview sent an incomplete copied node request.",
    nodeCopyUnchanged: "Copied node already matches the target position.",
    nodeCopyCreated: "Copied node inserted.",
    nodeCopyFailed: "Failed to insert copied node.",
    incompleteNodeDelete: "The webview sent an incomplete node delete request.",
    nodeDeleteUnchanged: "Node was already removed.",
    nodeDeleted: "Node deleted.",
    nodeDeleteFailed: "Failed to delete node.",
    xmlUpdateRejected: "VS Code rejected the XML update.",
    loadSettingsFailed: (message: string) => `BTreeTool: Failed to load user settings. ${message}`,
    settingsNotReady: "Settings could not be saved because the configuration file is not ready.",
    settingsSaved: "Settings saved.",
    settingsSaveFailed: (message: string) => `Failed to save settings. ${message}`,
    undoUnavailable: "No BTreeTool edit is available to undo.",
    undoApplied: "Undo applied.",
    undoFailed: "Failed to undo the last BTreeTool edit.",
    settingsFileNotReadyWarning: "BTreeTool: The user settings file is not ready yet.",
    settingsFileNotReady: "The user settings file is not ready yet.",
    presetsImported: "Recommended presets imported.",
    presetsImportFailed: (message: string) => `Failed to import recommended presets. ${message}`,
    importCustomNodesTitle: "Import TreeNodesModel nodes",
    customNodesImported: (count: number) => `Imported ${count} custom node definition${count === 1 ? "" : "s"}.`,
    customNodesImportEmpty: "No supported node definitions were found in the selected file.",
    customNodesImportSkipped: "Conflicting nodes were skipped. No new node definitions were imported.",
    customNodesConflictPrompt: (nodes: string) =>
      `The selected file has different content for existing nodes: ${nodes}. Choose how to continue.`,
    customNodesOverwriteAction: "Overwrite",
    customNodesSkipAction: "Skip",
    customNodesCancelAction: "Cancel",
    customNodesImportFailed: (message: string) => `Failed to import custom nodes. ${message}`,
    clearImportedNodesConfirm: "Restore the node library to the default preset? Imported nodes will be removed.",
    clearImportedNodesAction: "Restore",
    clearImportedNodesCanceledAction: "Cancel",
    importedNodesCleared: "Imported nodes cleared and the default node library was restored.",
    importedNodesClearFailed: (message: string) => `Failed to clear imported nodes. ${message}`,
    documentSaved: "XML file saved.",
    documentSaveFailed: "Failed to save the XML file.",
    documentSaveBlocked: "The current behavior tree has blocking issues and cannot be saved from the preview.",
    saveDocumentConfirm: "How do you want to save the current XML file?",
    saveAction: "Overwrite",
    saveAsAction: "Save As",
    saveCancelAction: "Cancel",
    saveAsXmlTitle: "Save BehaviorTree XML as",
    saveAsSameFileBlocked: "Choose a different file name for Save As.",
    openExistingXmlTitle: "Open existing BehaviorTree XML",
    newXmlNameTitle: "Confirm the new XML name",
    importPlaybackLogTitle: "Import Log"
  };

  if (!isChinese) {
    return base;
  }

  return {
    noAttachedDocument: "当前预览未附加 XML 文档。",
    incompleteNodeEdit: "Webview 发送的节点编辑请求不完整。",
    nodeAttributesUnchanged: "节点属性与当前 XML 已一致。",
    nodeAttributesApplied: "节点属性已应用。",
    nodeAttributesFailed: "应用节点属性失败。",
    noAttachedDocumentWarning: "BTreeTool：当前预览未附加 XML 文档。",
    incompleteTreeNodesModel: "Webview 发送的 TreeNodesModel 更新请求不完整。",
    treeNodesModelUnchanged: "TreeNodesModel 与当前 XML 已一致。",
    treeNodesModelUpdated: "TreeNodesModel 已更新。",
    treeNodesModelFailed: "更新 TreeNodesModel 失败。",
    incompleteBehaviorTreeCreate: "Webview 发送的 BehaviorTree 创建请求不完整。",
    createBehaviorTreeEmptyName: "BehaviorTree ID 不能为空。",
    createBehaviorTreeDuplicateName: (treeId: string) => `BehaviorTree“${treeId}”已经存在。`,
    behaviorTreeCreateUnchanged: "BehaviorTree 已存在。",
    behaviorTreeCreated: "BehaviorTree 已创建。",
    behaviorTreeCreateFailed: "创建 BehaviorTree 失败。",
    incompleteBehaviorTreeDelete: "Webview 发送的 BehaviorTree 删除请求不完整。",
    behaviorTreeDeleteUnchanged: "BehaviorTree 此前已被移除。",
    behaviorTreeDeleted: "BehaviorTree 已移除。",
    behaviorTreeDeleteFailed: "移除 BehaviorTree 失败。",
    incompleteNodeMove: "Webview 发送的节点移动请求不完整。",
    nodeOrderUnchanged: "节点顺序与当前 XML 已一致。",
    nodeOrderUpdated: "节点顺序已更新。",
    nodeOrderFailed: "节点重排失败。",
    incompleteNodeCreate: "Webview 发送的节点创建请求不完整。",
    nodeCreateUnchanged: "节点已经位于目标位置。",
    nodeCreated: "节点已创建。",
    nodeCreateFailed: "创建节点失败。",
    incompleteNodeCopy: "Webview 发送的复制节点请求不完整。",
    nodeCopyUnchanged: "复制节点已经位于目标位置。",
    nodeCopyCreated: "复制节点已插入。",
    nodeCopyFailed: "插入复制节点失败。",
    incompleteNodeDelete: "Webview 发送的节点删除请求不完整。",
    nodeDeleteUnchanged: "节点此前已被移除。",
    nodeDeleted: "节点已删除。",
    nodeDeleteFailed: "删除节点失败。",
    xmlUpdateRejected: "VS Code 拒绝了这次 XML 更新。",
    loadSettingsFailed: (message: string) => `BTreeTool：加载用户设置失败。${message}`,
    settingsNotReady: "配置文件尚未就绪，暂时无法保存设置。",
    settingsSaved: "设置已保存。",
    settingsSaveFailed: (message: string) => `保存设置失败。${message}`,
    undoUnavailable: "没有可撤销的 BTreeTool 编辑。",
    undoApplied: "已撤销。",
    undoFailed: "撤销上一次 BTreeTool 编辑失败。",
    settingsFileNotReadyWarning: "BTreeTool：用户设置文件尚未就绪。",
    settingsFileNotReady: "用户设置文件尚未就绪。",
    presetsImported: "推荐预设已导入。",
    presetsImportFailed: (message: string) => `导入推荐预设失败。${message}`,
    importCustomNodesTitle: "导入节点",
    customNodesImported: (count: number) => `已导入 ${count} 个自定义节点定义。`,
    customNodesImportEmpty: "所选文件中没有找到支持的节点定义。",
    customNodesImportSkipped: "已跳过冲突节点，没有导入新节点。",
    customNodesConflictPrompt: (nodes: string) =>
      `所选文件中这些节点与现有节点内容不同：${nodes}。请选择如何继续。`,
    customNodesOverwriteAction: "覆盖",
    customNodesSkipAction: "跳过",
    customNodesCancelAction: "取消",
    customNodesImportFailed: (message: string) => `导入自定义节点失败。${message}`,
    clearImportedNodesConfirm: "将节点库恢复为默认预设？导入的节点会被移除。",
    clearImportedNodesAction: "恢复",
    clearImportedNodesCanceledAction: "取消",
    importedNodesCleared: "已清除导入节点，并恢复默认节点库。",
    importedNodesClearFailed: (message: string) => `清除导入节点失败。${message}`,
    documentSaved: "XML 文件已保存。",
    documentSaveFailed: "保存 XML 文件失败。",
    documentSaveBlocked: "当前行为树存在阻断性问题，无法从预览窗口保存。",
    saveDocumentConfirm: "请选择当前 XML 文件的保存方式。",
    saveAction: "覆盖保存",
    saveAsAction: "另存为",
    saveCancelAction: "取消",
    saveAsXmlTitle: "另存为 BehaviorTree XML",
    saveAsSameFileBlocked: "另存为需要选择不同的文件名。",
    openExistingXmlTitle: "打开已有 BehaviorTree XML",
    newXmlNameTitle: "确认新 XML 的名称",
    importPlaybackLogTitle: "导入日志"
  };
}
